import { defineConfig } from 'vite';
import type { Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { viteSingleFile } from 'vite-plugin-singlefile';

/** Marks the published file as generated, so nobody edits it by hand. */
function generatedBanner(): Plugin {
  return {
    name: 'generated-banner',
    apply: 'build',
    transformIndexHtml: {
      order: 'post',
      handler: (html) =>
        html.replace(
          '<!doctype html>',
          '<!doctype html>\n<!-- Generated by "npm run build" from src/. Do not edit this file by hand. -->',
        ),
    },
  };
}

// The app is built into ONE self-contained HTML file (JS + CSS inlined).
// That file is served by GitHub Pages from the repository root (see scripts/publish-build.mjs),
// so there are no asset paths that could break under https://<user>.github.io/<repo>/.
export default defineConfig({
  root: 'src',
  base: './',
  publicDir: false,
  plugins: [react(), viteSingleFile(), generatedBanner()],
  build: {
    outDir: '../dist',
    emptyOutDir: true,
  },
});
