import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

// GitHub Pages serves the site from https://<user>.github.io/Testing/ (a sub-path, not the domain root).
// These checks make sure the production build contains nothing that would break there.
const html = readFileSync('index.html', 'utf8');
const config = readFileSync('vite.config.ts', 'utf8');

describe('production build is safe for GitHub Pages (sub-path /Testing/)', () => {
  it('Vite uses a relative base, never "/" (which would load assets from the domain root)', () => {
    expect(config).toMatch(/base:\s*'\.\/'/);
    expect(config).not.toMatch(/base:\s*'\/'/);
  });

  it('is one self-contained file: no external script, stylesheet or asset references', () => {
    expect(html).not.toMatch(/<script[^>]+\ssrc=/i);
    expect(html).not.toMatch(/<link[^>]+rel=["']stylesheet["']/i);
    expect(html).not.toMatch(/(?:src|href)=["']\/(?!\/)/); // no root-absolute paths such as /assets/x.js
    expect(html).not.toContain('main.tsx');
    expect(html).not.toContain('/src/');
  });

  it('contains the app root, the Hebrew RTL document and the generated-file notice', () => {
    expect(html).toContain('<div id="root"></div>');
    expect(html).toContain('lang="he" dir="rtl"');
    expect(html).toContain('Do not edit this file by hand');
  });

  it('does not load anything from the network (fonts, CDNs, analytics)', () => {
    const urls = [...html.matchAll(/https?:\/\/[^"'\s)]+/g)].map((m) => m[0]);
    // The only allowed URLs are plain text/links inside the app code, never resource loads.
    const loads = [...html.matchAll(/<(?:script|link|img|iframe)[^>]+(?:src|href)=["']https?:/gi)];
    expect(loads).toHaveLength(0);
    expect(urls.every((u) => !/googleapis|cdn|analytics|fonts\.g/.test(u))).toBe(true);
  });
});
